{"level":"error","message":"Internal error: Error: ReferenceError: accountErrorMessage is not defined","stack":"Error: Internal error: Error: ReferenceError: accountErrorMessage is not defined\n    at exports.loggerErrorMessage (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\src\\logMessages\\common.message.js:24:31)\n    at C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\src\\app.js:61:5\n    at Layer.handle_error (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\layer.js:71:5)\n    at trim_prefix (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:326:13)\n    at C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at Immediate.next (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Immediate._onImmediate (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:646:15)\n    at process.processImmediate (node:internal/timers:478:21)","timestamp":"2023-11-21T05:20:49.752Z"}
{"level":"error","message":"Internal error: Error: ReferenceError: accountErrorMessage is not defined","stack":"Error: Internal error: Error: ReferenceError: accountErrorMessage is not defined\n    at exports.loggerErrorMessage (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\src\\logMessages\\common.message.js:24:31)\n    at C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\src\\app.js:61:5\n    at Layer.handle_error (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\layer.js:71:5)\n    at trim_prefix (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:326:13)\n    at C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at Immediate.next (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Immediate._onImmediate (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:646:15)\n    at process.processImmediate (node:internal/timers:478:21)","timestamp":"2023-11-21T05:22:39.115Z"}
{"level":"error","message":"Internal error: Error: ReferenceError: accountErrorMessage is not defined","stack":"Error: Internal error: Error: ReferenceError: accountErrorMessage is not defined\n    at exports.loggerErrorMessage (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\src\\logMessages\\common.message.js:24:31)\n    at C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\src\\app.js:61:5\n    at Layer.handle_error (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\layer.js:71:5)\n    at trim_prefix (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:326:13)\n    at C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at Immediate.next (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Immediate._onImmediate (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:646:15)\n    at process.processImmediate (node:internal/timers:478:21)","timestamp":"2023-11-21T05:24:13.661Z"}
{"level":"error","message":"Internal error: [{\"message\":\"\\\"First Name\\\" is required\",\"field\":\"body_firstName\",\"type\":\"any.required\"}]","stack":"Error: Internal error: [{\"message\":\"\\\"First Name\\\" is required\",\"field\":\"body_firstName\",\"type\":\"any.required\"}]\n    at exports.loggerErrorMessage (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\src\\logMessages\\common.message.js:24:31)\n    at C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\src\\app.js:61:5\n    at Layer.handle_error (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\layer.js:71:5)\n    at trim_prefix (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:326:13)\n    at C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at Immediate.next (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Immediate._onImmediate (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:646:15)\n    at process.processImmediate (node:internal/timers:478:21)","timestamp":"2023-11-21T05:54:25.441Z"}
{"level":"error","message":"Internal error: [{\"message\":\"\\\"First Name\\\" is required\",\"field\":\"body_firstName\",\"type\":\"any.required\"}]","stack":"Error: Internal error: [{\"message\":\"\\\"First Name\\\" is required\",\"field\":\"body_firstName\",\"type\":\"any.required\"}]\n    at exports.loggerErrorMessage (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\src\\logMessages\\common.message.js:24:31)\n    at C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\src\\app.js:61:5\n    at Layer.handle_error (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\layer.js:71:5)\n    at trim_prefix (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:326:13)\n    at C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at Immediate.next (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Immediate._onImmediate (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:646:15)\n    at process.processImmediate (node:internal/timers:478:21)","timestamp":"2023-11-21T06:07:18.560Z"}
{"level":"error","message":"Internal error: [{\"message\":\"\\\"First Name\\\" is required\",\"field\":\"body_firstName\",\"type\":\"any.required\"}]","stack":"Error: Internal error: [{\"message\":\"\\\"First Name\\\" is required\",\"field\":\"body_firstName\",\"type\":\"any.required\"}]\n    at exports.loggerErrorMessage (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\src\\logMessages\\common.message.js:24:31)\n    at C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\src\\app.js:61:5\n    at Layer.handle_error (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\layer.js:71:5)\n    at trim_prefix (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:326:13)\n    at C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at Immediate.next (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Immediate._onImmediate (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:646:15)\n    at process.processImmediate (node:internal/timers:478:21)","timestamp":"2023-11-21T06:34:59.094Z"}
{"level":"error","message":"Internal error: {\"status\":401}","stack":"Error: Internal error: {\"status\":401}\n    at exports.loggerErrorMessage (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\src\\logMessages\\common.message.js:24:31)\n    at C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\src\\app.js:61:5\n    at Layer.handle_error (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\layer.js:71:5)\n    at trim_prefix (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:326:13)\n    at C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at Immediate.next (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Immediate._onImmediate (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:646:15)\n    at process.processImmediate (node:internal/timers:478:21)","timestamp":"2023-11-21T09:02:11.161Z"}
{"level":"error","message":"Internal error: {\"status\":401}","stack":"Error: Internal error: {\"status\":401}\n    at exports.loggerErrorMessage (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\src\\logMessages\\common.message.js:24:31)\n    at C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\src\\app.js:61:5\n    at Layer.handle_error (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\layer.js:71:5)\n    at trim_prefix (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:326:13)\n    at C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at Immediate.next (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Immediate._onImmediate (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:646:15)\n    at process.processImmediate (node:internal/timers:478:21)","timestamp":"2023-11-21T09:02:41.233Z"}
{"level":"error","message":"Internal error: {\"status\":401}","stack":"Error: Internal error: {\"status\":401}\n    at exports.loggerErrorMessage (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\src\\logMessages\\common.message.js:24:31)\n    at C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\src\\app.js:61:5\n    at Layer.handle_error (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\layer.js:71:5)\n    at trim_prefix (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:326:13)\n    at C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at Immediate.next (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Immediate._onImmediate (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:646:15)\n    at process.processImmediate (node:internal/timers:478:21)","timestamp":"2023-11-21T09:03:05.991Z"}
{"level":"error","message":"Internal error: {\"status\":401}","stack":"Error: Internal error: {\"status\":401}\n    at exports.loggerErrorMessage (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\src\\logMessages\\common.message.js:24:31)\n    at C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\src\\app.js:61:5\n    at Layer.handle_error (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\layer.js:71:5)\n    at trim_prefix (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:326:13)\n    at C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at Immediate.next (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Immediate._onImmediate (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:646:15)\n    at process.processImmediate (node:internal/timers:478:21)","timestamp":"2023-11-21T09:04:15.554Z"}
{"level":"error","message":"Internal error: {\"status\":400}","stack":"Error: Internal error: {\"status\":400}\n    at exports.loggerErrorMessage (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\src\\logMessages\\common.message.js:24:31)\n    at C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\src\\app.js:61:5\n    at Layer.handle_error (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\layer.js:71:5)\n    at trim_prefix (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:326:13)\n    at C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at Immediate.next (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Immediate._onImmediate (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:646:15)\n    at process.processImmediate (node:internal/timers:478:21)","timestamp":"2023-11-21T09:20:14.455Z"}
{"level":"error","message":"Internal error: {\"status\":401}","stack":"Error: Internal error: {\"status\":401}\n    at exports.loggerErrorMessage (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\src\\logMessages\\common.message.js:24:31)\n    at C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\src\\app.js:61:5\n    at Layer.handle_error (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\layer.js:71:5)\n    at trim_prefix (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:326:13)\n    at C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at Immediate.next (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Immediate._onImmediate (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:646:15)\n    at process.processImmediate (node:internal/timers:478:21)","timestamp":"2023-11-21T09:29:31.645Z"}
{"level":"error","message":"Internal error: {\"status\":401}","stack":"Error: Internal error: {\"status\":401}\n    at exports.loggerErrorMessage (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\src\\logMessages\\common.message.js:24:31)\n    at C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\src\\app.js:61:5\n    at Layer.handle_error (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\layer.js:71:5)\n    at trim_prefix (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:326:13)\n    at C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at Immediate.next (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Immediate._onImmediate (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:646:15)\n    at process.processImmediate (node:internal/timers:478:21)","timestamp":"2023-11-21T09:34:02.822Z"}
{"level":"error","message":"Internal error: {\"status\":401}","stack":"Error: Internal error: {\"status\":401}\n    at exports.loggerErrorMessage (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\src\\logMessages\\common.message.js:24:31)\n    at C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\src\\app.js:61:5\n    at Layer.handle_error (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\layer.js:71:5)\n    at trim_prefix (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:326:13)\n    at C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at Immediate.next (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Immediate._onImmediate (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:646:15)\n    at process.processImmediate (node:internal/timers:478:21)","timestamp":"2023-11-21T09:34:09.336Z"}
{"level":"error","message":"Internal error: ReferenceError: user is not defined","stack":"Error: Internal error: ReferenceError: user is not defined\n    at exports.loggerErrorMessage (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\src\\logMessages\\common.message.js:24:31)\n    at C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\src\\app.js:61:5\n    at Layer.handle_error (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\layer.js:71:5)\n    at trim_prefix (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:326:13)\n    at C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at Immediate.next (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Immediate._onImmediate (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:646:15)\n    at process.processImmediate (node:internal/timers:478:21)","timestamp":"2023-11-21T09:58:25.487Z"}
{"level":"error","message":"Internal error: Error: Error: Options must be an object, got \"-token\"","stack":"Error: Internal error: Error: Error: Options must be an object, got \"-token\"\n    at exports.loggerErrorMessage (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\src\\logMessages\\common.message.js:24:31)\n    at C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\src\\app.js:61:5\n    at Layer.handle_error (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\layer.js:71:5)\n    at trim_prefix (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:326:13)\n    at C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at Immediate.next (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Immediate._onImmediate (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:646:15)\n    at process.processImmediate (node:internal/timers:478:21)","timestamp":"2023-11-21T10:05:02.682Z"}
{"level":"error","message":"Internal error: Error: ReferenceError: res is not defined","stack":"Error: Internal error: Error: ReferenceError: res is not defined\n    at exports.loggerErrorMessage (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\src\\logMessages\\common.message.js:24:31)\n    at C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\src\\app.js:61:5\n    at Layer.handle_error (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\layer.js:71:5)\n    at trim_prefix (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:326:13)\n    at C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at Immediate.next (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Immediate._onImmediate (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:646:15)\n    at process.processImmediate (node:internal/timers:478:21)","timestamp":"2023-11-21T10:11:46.405Z"}
{"level":"error","message":"Internal error: [{\"message\":\"\\\"Last Name\\\" length must be at least 3 characters long\",\"field\":\"body_lastName\",\"type\":\"string.min\"}]","stack":"Error: Internal error: [{\"message\":\"\\\"Last Name\\\" length must be at least 3 characters long\",\"field\":\"body_lastName\",\"type\":\"string.min\"}]\n    at exports.loggerErrorMessage (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\src\\logMessages\\common.message.js:24:31)\n    at C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\src\\app.js:61:5\n    at Layer.handle_error (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\layer.js:71:5)\n    at trim_prefix (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:326:13)\n    at C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at Immediate.next (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Immediate._onImmediate (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:646:15)\n    at process.processImmediate (node:internal/timers:478:21)","timestamp":"2023-11-21T10:23:23.260Z"}
{"level":"error","message":"Internal error: {\"status\":401}","stack":"Error: Internal error: {\"status\":401}\n    at exports.loggerErrorMessage (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\src\\logMessages\\common.message.js:24:31)\n    at C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\src\\app.js:61:5\n    at Layer.handle_error (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\layer.js:71:5)\n    at trim_prefix (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:326:13)\n    at C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at Immediate.next (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Immediate._onImmediate (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\node_modules\\express\\lib\\router\\index.js:646:15)\n    at process.processImmediate (node:internal/timers:478:21)","timestamp":"2023-11-21T11:24:35.044Z"}
{"level":"error","message":"Internal error: {\"status\":401}","stack":"Error: Internal error: {\"status\":401}\n    at exports.loggerErrorMessage (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\server\\src\\logMessages\\common.message.js:24:31)\n    at C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\server\\src\\app.js:61:5\n    at Layer.handle_error (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\server\\node_modules\\express\\lib\\router\\layer.js:71:5)\n    at trim_prefix (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\server\\node_modules\\express\\lib\\router\\index.js:326:13)\n    at C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\server\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\server\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at Immediate.next (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\server\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Immediate._onImmediate (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\server\\node_modules\\express\\lib\\router\\index.js:646:15)\n    at process.processImmediate (node:internal/timers:478:21)","timestamp":"2023-11-21T13:10:46.485Z"}
{"level":"error","message":"Internal error: {\"status\":401}","stack":"Error: Internal error: {\"status\":401}\n    at exports.loggerErrorMessage (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\server\\src\\logMessages\\common.message.js:24:31)\n    at C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\server\\src\\app.js:61:5\n    at Layer.handle_error (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\server\\node_modules\\express\\lib\\router\\layer.js:71:5)\n    at trim_prefix (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\server\\node_modules\\express\\lib\\router\\index.js:326:13)\n    at C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\server\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\server\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at Immediate.next (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\server\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Immediate._onImmediate (C:\\Users\\codiant\\Desktop\\demoProjectSetupmongo\\server\\node_modules\\express\\lib\\router\\index.js:646:15)\n    at process.processImmediate (node:internal/timers:478:21)","timestamp":"2023-11-21T13:10:46.635Z"}
